### ISSUE TITLE
Search result URL needs to change

### ISSUE THREAD

**Issue by rickhg12hs** [OWASP/owasp.github.io#105]
FYI, searching for:  https://owasp.org/search/?searchString=intercept+proxies

returns a search result that points to: https://owasp.org/images/d/d8/Intercept-proxies.pdf

... but it's not found.

The correct URL is:  https://owasp.org/www-pdf-archive//Intercept-proxies.pdf

**Comment by Krshivam25** [comment]
Hey ! I'm new bee here how I can get the code file which have issue in this

**Comment by rickhg12hs** [comment]
@Krshivam25 I haven't really been following this, but I just checked and it seems to return correct URLs now.  Perhaps the search index just needed to be updated.

Since the original issue seems to be fixed, I'm closing this issue.
