### ISSUE TITLE
Use commit message

### ISSUE THREAD

**Issue by h3xstream** [OWASP/owasp.github.io#108]
The user/bot @OWASPFoundation is making commits without any information to describe the changes.

This makes it hard to down faulty change.

_(I assume the files are edited by a human since I have seen broken JSON committed.)_

**Comment by hblankenship** [comment]
Most of the commits are part of automation that runs once an evening (US time).  The commits are specific for certain files.  Explain the faulty change.

**Comment by h3xstream** [comment]
The project [Find Security Bugs](https://owasp.org/www-project-find-security-bugs/) was removed from https://owasp.org/projects/.
This is due to an edit in `_data/projects.json`.

**Comment by hblankenship** [comment]
I suspect it is because you are missing a required front matter item (level).  I added it to your index.md file.
