### ISSUE TITLE
Populate tab_flagships.md from existing content and meta data

### ISSUE THREAD

**Issue by bkimminich** [OWASP/owasp.github.io#11]
Instead of duplicating project listings and even descriptions, the `tab_flagships.md` might be better set up like this:

1. Select all projects with `level: 4`
2. Split them into groups by `type: code | tool | doc` to get the sub sections
3. Get project names from their `title` and their link from the naming convention of www-repos
4. Add a propery `pitch` for projects and display that as a description. Projects could then use that in their own page as well to avoid deviating content over time.

**Comment by hblankenship** [comment]
I like this and was thinking along this route as well but having already created the repos...well, do you think that would go over well?  new front matter requirement for description (keep it under a certain character count)?

**Comment by mikemccamon** [comment]
Yes good idea. Could a small bot be built to add a placeholder for #4 in all repos? Alternately could change template to diff out if a description is not present. If we could do it first alternative is best. We have only 30-40 odd projects migrated so far anyway.

**Comment by bkimminich** [comment]
And, this kind of page only exists for Flagships right now, no? Maybe you could use some placeholder text as default if no `pitch` is present, like `TODO` or `More info soon...`

**Comment by hblankenship** [comment]
It is now possible to add pitch: to your front matter; it should be short and to the point.  It should not contain newlines.  Anything added today should get built into the projects.json file at 8pm CST tonight.
