### ISSUE TITLE
Update from individual email address to JIRA tickert - Global Partnerships

### ISSUE THREAD

**Issue by latf6711** [OWASP/owasp.github.io#118]
please contact [Partnership Marketing](mailto:lisa.jones@owasp.com?subject=Partnership%20Marketing) TO https://owasporg.atlassian.net/servicedesk/customer/portal/7/group/19/create/83

**Comment by hblankenship** [comment]
And where is this? Please provide more context.

**Comment by hblankenship** [comment]
Nevermind. Contact us? Looks like it has been changed.
