### ISSUE TITLE
Add Mega-Linter in Code Quality Tools page

### ISSUE THREAD

**Issue by nvuillam** [OWASP/owasp.github.io#123]
Would it be possible to add Mega-Linter in the [list of Code Quality Tools](https://owasp.org/www-community/Source_Code_Analysis_Tools) ?

The content  would be the following:

[Mega-Linter](https://nvuillam.github.io/mega-linter/) |  | Open Source |   | analyzes 37 languages, 12 formats, 15 tooling formats , copy-pastes and spell in repository sources, generate reports in several formats, and can apply auto-fixes with auto-generated commit or PR, to ensure projects are clean, no matter what IDE/toolbox is used by their developers
-- | -- | -- | -- | --

**Comment by kingthorin** [comment]
Feel free to open a PR updating: https://github.com/OWASP/www-community/blob/master/_data/tools.json

**Comment by Shreyanshkhemesara** [comment]
Updated the tools.json for Mega-Linter.

**Comment by kingthorin** [comment]
I don't see any occurrences of "mega" in tools.json, nor do I recall a Pull Request to add it. So yup I'm guessing you've done something wrong.
