### ISSUE TITLE
Change in Membership cost while checking out

### ISSUE THREAD

**Issue by rtcms** [OWASP/owasp.github.io#128]
Whenever I apply for new membership request via https://owasp.org/membership/?student=yes (yes, I am student)
I am presented with $8 as the membership cost for 1 year

![Screenshot from 2020-12-07 13-07-35](https://user-images.githubusercontent.com/35173068/101322669-6f131d80-388d-11eb-99f4-08b51d2f91b0.png)

After I checkout , the price get's updated to $20 as 

![Screenshot from 2020-12-07 12-59-22](https://user-images.githubusercontent.com/35173068/101322764-910ca000-388d-11eb-93af-a4c1d5c66064.png)

Look's like Developing Economy Membership Pricing isn't applied as mentioned over here https://owasp.org/www-policy/operational/membership

**Comment by hblankenship** [comment]
Thank you. I am looking into it.

**Comment by hblankenship** [comment]
This should now be resolved.

**Comment by rtcms** [comment]
Awesome! Thanks for the update
