### ISSUE TITLE
Install Stale and Lock apps to allow auto-handling of unattended/historic issues

### ISSUE THREAD

**Issue by bkimminich** [OWASP/owasp.github.io#129]
Hi @hblankenship, could you please install the following two apps via the _Integration_ tab of the org _Settings_?

* https://github.com/apps/stale
* https://github.com/apps/lock

They allow convenient automatic handling of unattended issues (Stale) as well as locking of historic issues (Lock) to avoid someone commenting on them. Repos can decide to use them by placing a YAML file in a folder `.github`, so it's entirely opt-in. For an example config in active use see https://github.com/bkimminich/juice-shop/tree/master/.github. For the German Chapter I already prepare configs (https://github.com/OWASP/www-chapter-germany/tree/master/.github) which now just wait for the apps to be installed.

Thanks in advance! Merry 🎄 and cheers,
Björn

**Comment by bkimminich** [comment]
Hm, I just checked and I'm able to configure both apps on per-repo level, so I added them to https://github.com/OWASP/www-project-juice-shop. Can someone else please check if this is possible for anybody in the org team to do, or if I might have some special voodoo permissions? If the former, this ticket can be closed.

**Comment by kingthorin** [comment]
I believe this can be closed. Lock app has moved to GitHub actions and is no longer available. There are definitely stale GitHub actions as well.

Any projects are free to use either as they see fit.
