### ISSUE TITLE
owasp.org email instructions not being sent

### ISSUE THREAD

**Issue by mllanes** [OWASP/owasp.github.io#130]
Hi,
After a new membership registration and request for an owasp.org email, no instructions to access the inbox are ever sent (or received).

Steps to reproduce:

1- Sign up for a membership
2- Request an owasp.org email address. App will say that instructions are going to be sent to the registered email.

This may or may not be related to https://github.com/OWASP/owasp.github.io/issues/66

**Comment by hblankenship** [comment]
I see that your Owasp email address was provisioned as marcos.llanes@owasp.org.  You should have received an email from Google at your registered email address indicating that your account was set up (it is possible this went to Spam/Junk).  I have reset your password so you should receive another email shortly.  You will need to go to mail.google.com to login/update the password.

**Comment by tiwdurgesh** [comment]
Hi,
After a new membership registration and request for an owasp.org email, i received my email id but not sure how to login 

i tried the steps but couldn't

**Comment by pnc21** [comment]
Hello, i got membership how to request for owasp org mail id ?? i have no idea how to request for mail id
and no details were received its already been 1 month nearly so can anyone of you help me.

**Comment by pnc21** [comment]
@securestep9  I have done that but no response so contacted here for confirmation like what to do

**Comment by lenhantriet** [comment]
Hello members, I have a Gmail account at owasp.org and I've forgotten my password. I need your help to recover my account. My account is used for charitable work in provinces and cities across the country. I would be very grateful for your help in recovering my account. Thank you and I will reward you accordingly.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/95ee1550-9b21-45cd-8f8d-9b596e23ca28" />
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/8e17141c-7a22-4941-b7b7-f530ded928ab" />

**Comment by securestep9** [comment]
@lenhantriet the screenshot shows your OWASP membership expired on 19 March 2025 and your account may have been disabled because of this. Only active OWASP members have access to OWASP email. You can re-join OWASP here: https://owasp.org/join
