### ISSUE TITLE
URL rewriting to support friendly URLs

### ISSUE THREAD

**Issue by stevespringett** [OWASP/owasp.github.io#14]
URLs such as https://www2.owasp.org/www-project-dependency-track/ are not acceptable. 

Perception is reality. If this URL was published outside of OWASP, the perception would be that we don't know what we're doing. Trust will be questioned, etc.

So, we need friendly URLs. The URLs should NOT forward to the current structure, but simply render the page when using the friendly URL. What are the plans to support them and how can we access them prior to launch? This should be a MVP requirement.

For example:
https://projects.owasp.org/dependency-track
https://dependency-track.owasp.org
https://www.owasp.org/projects/dependency-track

I don't have a preference as long as it isn't https://www2.owasp.org/www-project-dependency-track/ which is quite embarrassing.

The Software Component Verification Standard project will be referenced in a future U.S. govt document. Having a URL such as https://www2.owasp.org/www-project-software-component-verification-standard/ does not exhibit trust. Rather something like:

https://projects.owasp.org/scvs
https://scvs.owasp.org
https://www.owasp.org/projects/scvs

would work much better.

**Comment by anantshri** [comment]
Some test notes that i did lately.  (took help from @hblankenship )

1. 301 redirects they can be set very easily as owasp.org is hosted on a apache server which can work as a redirector example 
https://owasp.org/chapter/bhopal -> https://www2.owasp.org/www-chapter-bhopal/
@hblankenship graciously set this up for testing

2. How can we keep url intact. I have tested by using a mod proxy in apache.
I have tried on local system not on the actual server but mod_proxy will have issues if the content in ssl on the end server as that results in cert mismatch errors
b) github either allows you to keep things http or https. If we keep github.io pages at http then we are basically connecting users 
client https  <-> owasp.org https <-> github http
which i suppose we will not recommend.

I am assuming at one point in future www2 will be just www and www i.e. mediawiki will go in readonly state at a different location.

these are rough notes in case someone tries experiments and feels confused.


+1 to the idea of projects or chapters subdomain with names on the side.

**Comment by hblankenship** [comment]
While I do agree that the look of the url is sub-optimal , I have to disagree about the sudden concern for the perception of the URLs being poorly received. 
 After all, you have been living with urls like this one: 

https://www.owasp.org/index.php/OWASP_Dependency_Track_Project

That said, we are discussing the various possibilities.  As a side note, the idea moving forward with regard to www2 is to drop it and just have owasp.org (no www).  The wiki will probably move to wiki.owasp.org.

**Comment by stevespringett** [comment]
https://www.owasp.org/index.php/OWASP_Dependency_Track_Project was something I had no control over. It's also the reason why https://dependencytrack.org/ exists. I use that - not the OWASP URL. Other flagship projects have similar approaches. The perception concern is not new.

However, this is an opportunity to get it right. To make it less of a need to go outside of whats provided by OWASP for hosting a project site.

**Comment by kerberosmansour** [comment]
@stevespringett @hblankenship is this a show stopper or something that can be updated at a later time? 

Does gitpages provide an alternative approach @stevespringett  do you have a proposed alternative for @hblankenship to consider?

@hblankenship what other options does github provide? IS the same page able to point to 2 domains? e.g. https://www2.owasp.org/www-project-dependency-track/ AND https://dependencytrack.org/ at the same time?

**Comment by kingthorin** [comment]
> Is it not possible to deploy the content to a URL that's a different value from the repo name?
> 
> Ex: Could https://github.com/OWASP/www-project-testing deploy as https://www2.owasp.org/project-testing or https://www2.owasp.org/testing-guide instead of "https://www2.owasp.org/www-project-testing/" as it is now?
> 
> Ref: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/

**Comment by kerberosmansour** [comment]
> > Is it not possible to deploy the content to a URL that's a different value from the repo name?
> > Ex: Could https://github.com/OWASP/www-project-testing deploy as https://www2.owasp.org/project-testing or https://www2.owasp.org/testing-guide instead of "https://www2.owasp.org/www-project-testing/" as it is now?
> > Ref: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/

@hblankenship would that work? And if so can it be done for a later release?

**Comment by bkimminich** [comment]
Wouldn't we lose analytic data by hosting the pages on our own outside GitHub?

**Comment by hblankenship** [comment]
Using the baseurl does not seem to work for this purpose.

**Comment by oxdef** [comment]
@hblankenship Jekyll supports feature called [permalinks](https://jekyllrb.com/docs/permalinks/). Can  it helps us? I already use it for my own site hosted at GitHub and [it works](https://github.com/oxdef/oxdef.github.io).

**Comment by anantshri** [comment]
> @hblankenship Jekyll supports feature called [permalinks](https://jekyllrb.com/docs/permalinks/). Can it helps us? I already use it for [my own site](https://github.com/oxdef/oxdef.github.io) hosted at GitHub and [it works](https://oxdef.info/foo-bar).
> 
> UPD: I've tested this feature on [www-chapter-moscow](https://github.com/OWASP/www-chapter-moscow). As a result I got working URL `https://www2.owasp.org/www-chapter-moscow/foobar` but not `https://www2.owasp.org/foobar` :( Looks like repository name is always (?) used as `baseurl`.
> So as for now I see following opportunities to get friendly URLs:
> 
> 1. Name convention in GitHub for projects and chapters without `www` like `chapter-moscow`. To separate `www` projects from the others `topics` feature can be used (e.g. https://github.com/topics/owaspwww). In such scenario final URLs will be `https://owasp.org/chapter-moscow` or `https://owasp.org/project-dependency-track`
> 2. Some kind URL rewriting engine (e.g. nginx) before the site...

Topics looks like an interesting way but i am not sure if people want to go that way. topics are global so if anyone adds a topic they would start getting listed in that page. exactly something we would not want to have.

URL rewrite has its own issues. I have described my tests in https://github.com/OWASP/owasp.github.io/issues/14#issuecomment-551930907

**Comment by oxdef** [comment]
> topics are global so if anyone adds a topic they would start getting listed in that page

Yes, but we can filer repositories by org. For example, this query shows only repositories from OWASP with topic `owaspwww` https://github.com/search?q=topic%3Aowaspwww+org%3Aowasp&type=Repositories

I really like idea with hosting of OWASP site on GitHub pages. But of course it has cons and pros. To have friendly URLs without external rewrite engine we need to rename project/chapter repositories. URLs like `https://www.owasp.org/index.php/OWASP_Dependency_Track_Project ` were really terrible.

**Comment by victoriadrake** [comment]
To truly make use of GitHub Pages, the [repositories should be renamed](https://help.github.com/en/github/working-with-github-pages/about-github-pages#types-of-github-pages-sites) to remove any "www-" or "owasp-" prefixes, which, colloquially, look really silly. There's little need for this differentiation on GitHub when users can easily search for any project.

If the `owasp.github.io` repository will be using the `owasp.org` [custom domain](https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site), the only Pages-based redirection solution I see is to have dead placeholder repos with the old "www-" prefixed names that host a redirection page.

Redirection would be handled in a cleaner manner by the Apache server as mentioned above, if it will still be in play after the move.

**Comment by cw-owasp** [comment]
Can we just rename our own repositories? There seems to be an option to do this in Settings, but I haven’t risked doing it.

**Comment by kingthorin** [comment]
@cw-owasp The naming exists as-is (at least in part) to facilitate some automation/backend jobs. If you rename the repo(s) then other things will break.

**Comment by cw-owasp** [comment]
@kingthorin I see, but some project repos don’t match the www-project- prefix.

**Comment by kingthorin** [comment]
Those are probably actual project repos.

**Comment by hblankenship** [comment]
renaming the repository will break certain things in the site (including
removing your project/chapter from the list of projects/chapters) so it is
not recommended.

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

**Comment by ThunderSon** [comment]
@kingthorin this was properly tackled, correct?

**Comment by kingthorin** [comment]
Well not quite. We have friendly redirects now, but still no rewriting that could be used for deep linking with friendly URLs.

Ex: It's handy that owasp.org/top10 redirects to owasp.org/www-project-top-10 for social media, slide decks, business cards, stickers, etc. However you can't do something like: https://owasp.org/top10/OWASP_Top_Ten_2017/

**Comment by ThunderSon** [comment]
I think that could be accomplished if we create folders inside of the redirects per project, and then each project would set a variable that controls that. Workaround definitely, it would mimic the same behavior.
`redirects -> top10 -> <file_name1>.md , <file_name2>.md` and inside of the files the variable which is being called? Still trying to think about it.

**Comment by hblankenship** [comment]
No plans to support this sort of redirect outside of the current redirect method in owasp.github.io
