### ISSUE TITLE
CycloneDX redirect is not working

### ISSUE THREAD

**Issue by stevespringett** [OWASP/owasp.github.io#148]
When going to [https://owasp.org/cyclonedx](https://owasp.org/cyclonedx), rather than being forwarded, the browser is prompted to download a file. The payload for the file is below:

```html
<!DOCTYPE html>
<html lang="en-US">
  <meta charset="utf-8">
  <title>Redirecting&hellip;</title>
  <link rel="canonical" href="http://owasp.org/www-project-cyclonedx/">
  <script>location="http://owasp.org/www-project-cyclonedx/"</script>
  <meta http-equiv="refresh" content="0; url=http://owasp.org/www-project-cyclonedx/">
  <meta name="robots" content="noindex">
  <h1>Redirecting&hellip;</h1>
  <a href="http://owasp.org/www-project-cyclonedx/">Click here if you are not redirected.</a>
</html>
```

Looks like there's a few things wrong with this including the script location and the fact its http rather than https.

**Comment by hblankenship** [comment]
You may have to clear cache (or use DevTools) but this should now be fixed.  File did not end in .md

**Comment by stevespringett** [comment]
Ugh. My bad. Thanks for correcting.
