### ISSUE TITLE
Remove (or clarify) GitHub status on page

### ISSUE THREAD

**Issue by stevespringett** [OWASP/owasp.github.io#15]
Currently on project and chapter pages (others as well), there are Github watch, star, and issue buttons. These are specific to the webpage not the project itself. For example:

<img width="1267" alt="Screen Shot 2019-11-08 at 11 58 07 AM" src="https://user-images.githubusercontent.com/3878933/68499706-76e23780-021f-11ea-9475-3286b5ddf993.png">

This looks like a really unpopular project. If I was visiting the site for the first time and saw this, I would not want to use it. I would see that only a few people have stared it, nobody's using it (0 issues), so therefore I wouldn't give it any consideration. The reality is very much different. Same can be said for every flagship project.

I would highly recommend removing these buttons. They do not add any value to the page. If there is some reason why they are there, then I encourage the site template to also include the watchers, stars, and issues from the actual software repos themselves. This might be a bit more difficult as you'll likely need to aggregate them (most projects have more than one repo).

Easiest way would be to simply remove it.

**Comment by stevespringett** [comment]
In addition, if someone wanted to watch a specific page for updates, then can simply go to the repo (assuming they can find it in the current mess), and watch/star it there.

**Comment by hblankenship** [comment]
This has been brought up in a different issue by Bjoern.  The result is that you may now include in your config.yml file a link to your code repository (which will be used).  Note the following:

code_user: bkimminich
code_repo: juice-shop

cheers!

**Comment by stevespringett** [comment]
Thanks @hblankenship. That worked. For mono-repos, I think this approach works fine but for projects with multiple repos, it will quickly break down. Currently SCVS is a mono repo and the majority of Dependency-Track is a mono-repo (although that will be changing in the near future). So I think I'll close this for now. A possible future improvement may be to support aggregated stats or multiple repos.

**Comment by bkimminich** [comment]
Ususally there would be one "main" repo of each project, no? Configuring that via the `code_user`/`code_repo` properties and adding other repos via https://shields.io/category/social badges to one of the project page tabs might be sufficient for multi-repo projects?
