### ISSUE TITLE
Missing Chapters in Chapter Listings (Birmingham)

### ISSUE THREAD

**Issue by derweiser** [OWASP/owasp.github.io#150]
Harold, missing Birmingham UK and Birmingham, Alabama from the Chapter listing pages. thanks

**Comment by OWASPFoundation** [comment]
I see Birmingham, UK in the list as of today and Birmingham, Alabama is not in the list because their chapter page has never been updated (and so they are not considered 'active' until it is updated). I verified that the json data was updated as of last night (updated nightly).

**Comment by derweiser** [comment]
Thanks, that's great
