### ISSUE TITLE
broken link on  SecureTea Project

### ISSUE THREAD

**Issue by shubhangi013** [OWASP/owasp.github.io#158]
The link pre-requisites under installation in [here](https://owasp.org/www-project-securetea/) gives a 404 error, it must lead to [this link](https://github.com/OWASP/SecureTea-Project/blob/master/doc/en-US/user_guide.md#pre-requisites).
I can fix this error so assign me this issue. Thank you!

**Comment by hblankenship** [comment]
you should open a PR on the SecureTea project repository instead of here. https://owasp.org/www-project-securetea/
