### ISSUE TITLE
Seach page CCS Issue Text overflowing from the sort by button

### ISSUE THREAD

**Issue by kerberosmansour** [OWASP/owasp.github.io#16]
See image from the search page looks like the CCS is off:
https://www2.owasp.org/search?searchString=London
Note the 'e' in date is not in the button
![Screenshot 2019-11-11 at 19 34 27](https://user-images.githubusercontent.com/13433538/68615153-6bf70380-04ba-11ea-8a59-578db828e808.png)

**Comment by bkimminich** [comment]
![image](https://user-images.githubusercontent.com/3531020/68624006-16c8eb00-04d6-11ea-9c47-1701cc59f982.png)

**Comment by martinmarsicano** [comment]
Thanks @hblankenship 

@kerberosmansour and @bkimminich can you check if this fixes your issues?

**Comment by kingthorin** [comment]
https://github.com/OWASP/www--site-theme/pull/81 was merged so this is hopefully now fixed

**Comment by martinmarsicano** [comment]
@kerberosmansour told me that he checks and it's fixed for him.

@bkimminich can you check if this is fixed for you and if it is, close the issue?
