### ISSUE TITLE
US AppSec conf banner keeps reopening

### ISSUE THREAD

**Issue by bkimminich** [OWASP/owasp.github.io#165]
With the exception of items from the _Projects_ menu every menu item on the OWASP website will reopen the annoying US AppSec conference banner. Closing it via the X-button is seemingly not persisted in a way that would consistently keep it closed.

This is a related issue to #164 but worse as it happens on desktop Browsers as well. Tested in Chrome and Firefox.

## Visits owasp.org
![image](https://user-images.githubusercontent.com/3531020/140692060-0269525d-3dec-47ac-85e4-66dd19d169e2.png)

## X banner closed
![image](https://user-images.githubusercontent.com/3531020/140692085-9d56c9fe-00af-4139-97d7-b293933ace1b.png)

## Pick any menu item (not from Projects)
![image](https://user-images.githubusercontent.com/3531020/140692184-853a59f6-06fd-44ff-a97c-c84a17734bb3.png)

## Banner comes back
![image](https://user-images.githubusercontent.com/3531020/140692222-92e12214-3d7e-4988-adea-c4d37e316cd1.png)

**Comment by hblankenship** [comment]
Clicking X will now properly keep the dialog hidden

**Comment by bkimminich** [comment]
Thank you! 👍

**Comment by commjoen** [comment]
Thanks @hblankenship !
