### ISSUE TITLE
Flagships tab is empty right now

### ISSUE THREAD

**Issue by bkimminich** [OWASP/owasp.github.io#17]
![image](https://user-images.githubusercontent.com/3531020/68624107-64ddee80-04d6-11ea-821f-67bcf8f3fd01.png)

Can't see if this is related to #11 in general or maybe some `pitch` containing unexpected characters. Can we see the build results of Jekyll somewhere maybe?

**Comment by hblankenship** [comment]
I believe this is fixed.
