### ISSUE TITLE
Staff info page 404

### ISSUE THREAD

**Issue by kingthorin** [OWASP/owasp.github.io#173]
On https://owasp.org/corporate/  the link to https://owasp.org/www-staff/operating-plan/status-2021 404s and there doesn’t seem to be a 2022 resource.

**Comment by hblankenship** [comment]
This should now be resolved.

**Comment by kingthorin** [comment]
Agreed it seems good, will it eventually be replaced by 2022 content/link?

(Either way you’re good to close this.)

**Comment by hblankenship** [comment]
Yes, it will get updated.
