### ISSUE TITLE
Project "OWASP Secure Headers Project" leaders update

### ISSUE THREAD

**Issue by righettod** [OWASP/owasp.github.io#175]
Hi,

It is possible to add me as additional leader of the [OWASP Secure Headers Project](https://owasp.org/www-project-secure-headers/) ?

![image](https://user-images.githubusercontent.com/1573775/151586996-1eff2748-dbe2-4ed1-a31b-13a5558c163c.png)

Dominique Righetto - dominique.righetto@owasp.org

![image](https://user-images.githubusercontent.com/1573775/151586741-ed09725a-d918-4dc5-b1c0-6772fce03b48.png)

Thank you very much in advance 😃

**Comment by hblankenship** [comment]
Someone needs to update the leaders.md file to remove the Co-leaders line. There is no such thing as Co-leaders. It should, instead, say:

Leaders
Ricardo Iramar
Alexandre Menezes
Dominique Righetto

If you do not have access to the repository, you will need to ask one of the other leaders to do it.
