### ISSUE TITLE
ensure all resources are on owasp.org domain using CNAME due to enterprise blocking

### ISSUE THREAD

**Issue by securestep9** [OWASP/owasp.github.io#18]
Most enterprise environments BLOCK access to GitHub.com and github.io domains from their corporate networks - companies like banks/finance/legal/insurance/pharmaceuticals/utilities etc. This is usually due to data leakage risks and unauthorised software download reasons.

Things like file attachments (e.g. slide decks), images, buttons seemed to be affected the most at the moment.

To make sure that OWASP's new website content is available to everyone we need to CNAME to owasp.org all github.com domains such as:

githubassets.com
GitHub.com
github.io (already implemented)

**Comment by roberto-at-acrosec** [comment]
A similar issue regarding emails coming from OWASP which contain weird links you wouldn't associate with OWASP. I will open a ticket.

**Comment by hblankenship** [comment]
cannot assign CNAME owasp.org to multiple targets
