### ISSUE TITLE
Legacy website URL redirection is broken

### ISSUE THREAD

**Issue by pierre-loup-tristant-sonarsource** [OWASP/owasp.github.io#182]
Beginning of July I noticed that the website stopped redirecting the URLs from the old website to the new one. As an example, https://www.owasp.org/index.php/Top_10-2017_A3-Sensitive_Data_Exposure now returns a 404 while a few weeks ago it was redirecting to  https://www.owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure. Do you know if this is intended or not?

Thank you.

**Comment by hblankenship** [comment]
Thank you for pointing this out; apparently our redirecting service went south at some point. I believe this should now be resolved.

**Comment by pierre-loup-tristant-sonarsource** [comment]
I can confirm that it works again. Thant for fixing the problem.
