### ISSUE TITLE
Links to anchors in CheatSheet pages not working

### ISSUE THREAD

**Issue by GeorgesBolssens-Toreon** [OWASP/owasp.github.io#183]
Reproduction
1. Go to https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_CheatSheet.html
2. Click one of the hyperlinks in the navigation

Expected result: Browser jumps to that section
Actual result: Nothing happens

Tested in Safari 15.5, Chrome 104, Firefox 103.0.2

**Comment by hblankenship** [comment]
Could you open this ticket on the https://github.com/OWASP/CheatSheetSeries repository?

**Comment by GeorgesBolssens-Toreon** [comment]
Done; I was not aware that that repo existed.
