### ISSUE TITLE
Security.txt file for owasp.org

### ISSUE THREAD

**Issue by cqueern** [OWASP/owasp.github.io#185]
Wondering if we might implement a security.txt file for owasp.org at this URL:

https://owasp.org/.well-known/security.txt

Security.txt files make it easier for researchers to report vulnerabilities to organizations, in this case to OWASP itself.

Background

- [RFC](https://www.rfc-editor.org/rfc/rfc9116)
- [Security.txt file generator](https://securitytxt.org/)

**Comment by cqueern** [comment]
OWASP recommends the use of security.txt in its Cheatsheet series [here](https://cheatsheetseries.owasp.org/cheatsheets/Vulnerability_Disclosure_Cheat_Sheet.html#finding-contact-details).

**Comment by hblankenship** [comment]
This has been implemented.

**Comment by cqueern** [comment]
Hi @hblankenship . When I go to https://owasp.org/.well-known/security.txt I get a 404 message instead of the expected text file. Is that intended behavior at the moment?
![Screen Shot 2022-08-29 at 12 34 01 PM](https://user-images.githubusercontent.com/1588185/187263429-4a34283b-d08c-4bdc-ab30-25c5f6c9491a.png)

**Comment by hblankenship** [comment]
Ah, thanks. I forgot to enable that .well-known folder

**Comment by cqueern** [comment]
Looks great, thanks @hblankenship
