### ISSUE TITLE
Fix Side Menu

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp.github.io#19]
On mobile at least once the menu is clicked, there's no way to close it. It would be great if this can be fixed! Thanks :)

![Screenshot_20191114-133612](https://user-images.githubusercontent.com/29175115/68871672-18282c80-06fd-11ea-81f9-00855162c5f3.jpg)
![Screenshot_20191114-133617](https://user-images.githubusercontent.com/29175115/68871680-1c544a00-06fd-11ea-8944-8a79d5ce6ec7.jpg)

**Comment by hblankenship** [comment]
fixed though may require a build for all sites (was in theme)

**Comment by cpholguera** [comment]
Thanks Harold, should/can we trigger that ourselves for the MSTG site?

**Comment by hblankenship** [comment]
I triggered a site-wide build but that doesn't always work.  To do it for
your own repo, just update the index.md file (I usually put a  type line and edit that.

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

**Comment by cpholguera** [comment]
Perfect. We'll check and do that if it's not directly fixed. Thanks again!

**Comment by cpholguera** [comment]
It's fixed. I can already confirm. Thank you for the quick fix ☺️
