### ISSUE TITLE
An adequate Replacement for Mediawiki Templates is needed

### ISSUE THREAD

**Issue by sslHello** [OWASP/owasp.github.io#20]
In my opinion we do need a good replacement for the mediawiki templates.
There is a need to provide OWASP-wide templates and locally managed templates.
I've have found a candidate for such a replacement: https://gohugo.io/content-management/shortcodes/  Sorry I don't have any experience with it. Please verify if it works or give us an other replacement and give us guidelines how to use it.

I am sorry to say, but in my opinion this is a critical factor for any migration.
Cheers Torsten

**Comment by hblankenship** [comment]
Could you provide an example of what you are trying to accomplish with 'templates'?

**Comment by Neil-Smithline** [comment]
Harold - Look at one of the T10 pages - for example, [2017-A1](https://www.owasp.org/index.php?title=Top_10-2017_A1-Injection). The header, navigation, footer, and general format of the page is all managed by templates. View the source for that page and you'll see. 

We use the templates for providing consistent formatting and I18N throughout the T10. You can dig down into the source for any individual template, but that's not really interesting (and a bit sickening due to Mediawiki syntax). The key is that we're able to provide consistent formatting and content across dozens of pages.

**Comment by sslHello** [comment]
Hi Harold,
you get a list of all used templatey by a page using 'Page information' on the bottom left menue, e.g.: https://www.owasp.org/index.php?title=Top_10-2017_A1-Injection&action=info
There are also templates that are used by different projects up to the entire wiki, e.g. https://www.owasp.org/index.php/Template:Contact. You can see the uahe by clicking on 'What links here', e.g. https://www.owasp.org/index.php/Special:WhatLinksHere/Template:Contact
This gives us the opportunity to define reusable design and content that can be centrally managed.
There is an huge number of different templates in use. Additionally you can get some statictics about templates needing maintainance via https://www.owasp.org/index.php/Special:SpecialPages
Cheers Torsten

**Comment by sslHello** [comment]
Hi Harold,
I am sorry, may I ask if there is any progess on this?
I realy don't know how to migrate wiki pages without this feature. In my opinion it looks very likely to create an unstructured mess while massively duplicating content. The maintainance will be a nightmare...
Cheers Torsten

**Comment by kingthorin** [comment]
Any repo can define project/chapter `_includes` or `_layouts`. If you want to contribute such globally just open a PR against `OWASP/www--site-theme`

- https://jekyllrb.com/docs/includes/
- https://jekyllrb.com/docs/layouts/

**Comment by sslHello** [comment]
@kingthorin: Thank you for your information.
We have compiled a version  of the 'full-width.html' layout.
I am happy to contribute this layout and includes that we have compiled for the Top 10 Project:
[https://github.com/OWASP/www--site-theme/pull/58](https://github.com/OWASP/www--site-theme/pull/58#issue-409101538)
I do hope it suits to other documentation projects, too.
