### ISSUE TITLE
GitHub link is missing in OWASP Foundation main site.

### ISSUE THREAD

**Issue by KhanalGaurab** [OWASP/owasp.github.io#203]
![image](https://user-images.githubusercontent.com/122043020/211362091-085ab0fe-e32a-491b-a766-cdd38139ee85.png)

At right bottom of the page we can see many different site with it's logo where we can know more about OWASP Foundation  and also contact OWASP Foundation but GitHub link is missing there due to which many new contributors may find difficult to find official GitHub page of OWASP Foundation through OWASP Foundation main site.

**Comment by KhanalGaurab** [comment]
Can I work on this issue? Please assign me this issue.

**Comment by KhanalGaurab** [comment]
How to run Locally?

**Comment by kingthorin** [comment]
> How to run Locally?

https://owasp.org/migration/#setup-a-local-testing-environment

**Comment by KhanalGaurab** [comment]
Can I work on this issue? Please assign me this issue.

**Comment by kingthorin** [comment]
Sorry Khanal you closed it not planned so I went ahead and PRd the addition yesterday.

**Comment by KhanalGaurab** [comment]
> Sorry @KhanalGaurab you closed this as not planned so I went ahead and PRd the addition yesterday.
It's ok. Can you guide me on how to run locally? @kingthorin  I am getting error when I run command "bundle install" - Step number 3.
![image](https://user-images.githubusercontent.com/122043020/211562563-0850c23e-1487-4c9e-a567-8849d07789a9.png)
Error message: 
Installing nokogiri 1.13.10 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

An error occurred while installing nokogiri (1.13.10), and Bundler cannot
continue.

In Gemfile:
  github-pages was resolved to 227, which depends on
    jekyll-mentions was resolved to 1.6.0, which depends on
      html-pipeline was resolved to 2.14.3, which depends on
        nokogiri

**Comment by kingthorin** [comment]
I don't know off the top of my head. I'd have to build a clean VM to reproduce on. Some suggestions:

1. Permissions? Try sudo'ing the install.
2. Ruby version issue? Look into rbenv (I think that's what it's called).
3. Find an OWASP repo that does run locally and copy that Gemfile.
🤷
