### ISSUE TITLE
Image URLs with minus character (-) are getting rewritten

### ISSUE THREAD

**Issue by stevespringett** [OWASP/owasp.github.io#22]
The Dependency-Track repo has an embedded image. The URL to the image contains a minus sign which is getting stripped out resulting in a 404 and the image not displaying.

This page
https://github.com/OWASP/www-project-dependency-track/blob/master/tab_integrations.md

Refers to this image:
https://raw.githubusercontent.com/DependencyTrack/dependency-track/master/docs/images/integrations.png

But the rendered page from the Integrations tab of
https://www2.owasp.org/www-project-dependency-track/

is referring to:
https://raw.githubusercontent.com/DependencyTrack/dependencytrack/master/docs/images/integrations.png which does not exist.

This is a regression with the site or template, as when the page was created, this image was displaying just fine. A site-wide change in the past month resulted in this regression. Once corrected, there should be tests created to ensure it doesn't happen again.

**Comment by hblankenship** [comment]
This has been resolved.

**Comment by stevespringett** [comment]
Fantastic. Thanks @hblankenship
