### ISSUE TITLE
Set the copyright license

### ISSUE THREAD

**Issue by nemobis** [OWASP/owasp.github.io#23]
This repository currently lacks a copyright statement and a public license. Currently there are only 6 contributors https://github.com/OWASP/owasp.github.io/graphs/contributors but you'd better hurry up and add a license before other people start contributing, otherwise OWASP will end up not having copyright on its own website.

Considering that you're importing content from the wiki, which is under CC-BY-SA 4.0 at the moment, you'll need to use the same license.

**Comment by kingthorin** [comment]
https://github.com/OWASP/owasp.github.io/blob/master/LICENSE

**Comment by fredfalcon** [comment]
This issue can be closed
