### ISSUE TITLE
"Membership Success" Page Indexed and Unrestricted

### ISSUE THREAD

**Issue by AlphaKiloDelta** [OWASP/owasp.github.io#230]
Hello,

Is [this page](https://owasp.org/membership-success/) intended to be indexed and unrestricted? You would expect only newly registered members to be directed to a page saying "Thank you for becoming a member", however this page is indexed on all major search engines and can be accessed by anyone.

The web team may want to add a `robots` meta tag with the `noindex` value to this page, and disallow it in the robots.txt file (if the site has one). May also want to ensure that non-newly registered members accessing the path are redirected to the homepage instead.

Not so much a concern, just an optimisation which could be made.

Thank you.

**Comment by vanderaj** [comment]
Thank you for letting us know. I'll get Harold to have a look.

**Comment by chnrv99** [comment]
I have made a PR here https://github.com/OWASP/owasp.github.io/pull/290 where I updated the robots.txt file
Please look into it

**Comment by vanderaj** [comment]
Thank you - fixed and merged
