### ISSUE TITLE
Reported to authorities

### ISSUE THREAD

**Issue by SebastianBotez** [OWASP/owasp.github.io#234]
Hello :)
Since you guys don't have any email address on your website to contact you, I wanna inform you that you guys tried to brute force one of our client's system and the authorities and the informatic police has been noticed for fraudulent behaviour.

33597 | https://\568167580631256015.owasp.org | ZAP | 185.246.188.74 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 00:14 23-04-2023
-- | -- | -- | -- | -- | --
33598 | //568167580631256015.owasp.org | ZAP | 185.246.188.74 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 00:14 23-04-2023
33594 | 5;URL='https://568167580631256015.owasp.org' | ZAP | 185.246.188.74 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 00:14 23-04-2023
33595 | URL='http://568167580631256015.owasp.org' | ZAP | 185.246.188.74 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 00:14 23-04-2023
33596 | http://\568167580631256015.owasp.org | ZAP | 185.246.188.74 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 00:14 23-04-2023
33592 | https://568167580631256015.owasp.org | ZAP | 185.246.188.74 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 00:14 23-04-2023
33593 | https://568167580631256015%2eowasp%2eorg | ZAP | 185.246.188.74 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 00:14 23-04-2023
33590 | 568167580631256015.owasp.org | ZAP | 185.246.188.74 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 00:14 23-04-2023
33591 | http://568167580631256015.owasp.org | ZAP | 185.246.188.74 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 00:14 23-04-2023
33564 | www.google.com:80/search?q=OWASP%20ZAP | ZAP | 185.243.218.46 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 23:56 22-04-2023
33563 | www.google.com:80/search?q=OWASP%20ZAP | ZAP | 185.243.218.46 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 23:56 22-04-2023
33562 | www.google.com/search?q=OWASP%20ZAP | ZAP | 185.243.218.46 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 23:56 22-04-2023
33554 | http://www.google.com:80/search?q=OWASP%20ZAP | ZAP | 185.243.218.46 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0 | 23:56 22-04-2023

And the list goes on.
Good luck with the legal process.

**Comment by psiinon** [comment]
Er no, this does  not mean one of us tried to attack one of your clients systems.
It does mean that someone tried to use OWASP ZAP to attack your systems, but we dont know who.
ZAP is a free security tool that anyone can download. It allows you to test your own systems before putting them on the internet, where someone is bound to attack them.
Note that there is a "Contact Us" link on the main https://owasp.org site which links to https://owasp.org/contact/

**Comment by vanderaj** [comment]
Simon is right. If there is anything else, please use the contact link above.
