### ISSUE TITLE
Import history of the pages

### ISSUE THREAD

**Issue by nemobis** [OWASP/owasp.github.io#24]
From https://github.com/OWASP/owasp.github.io/graphs/commit-activity it's apparent that the history of the pages has not been imported yet.

If you don't import the history, there are a few issues, chiefly:
* authors are not attributed, which is probably a copyright violation unless OWASP got all copyrights assigned by all wiki users;
* permanent links to the wiki cannot be redirected to a meaningful target.

See https://www.mediawiki.org/wiki/Help:Export on how to export MediaWiki content.

**Comment by hblankenship** [comment]
history will not be imported from the wiki to the website
