### ISSUE TITLE
Grammar mistakes - Unrestricted File Upload page

### ISSUE THREAD

**Issue by 5t00g1t** [OWASP/owasp.github.io#244]
Hi there, apologies if I am not following the correct procedure but wanted to let you know about a few grammar mistakes on this page: https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload

Should be ‘needs’
![image](https://github.com/OWASP/owasp.github.io/assets/29344572/38081579-5de4-44fb-9b71-ed6a73835a22)

Should be ’in 'a' gif file
![image](https://github.com/OWASP/owasp.github.io/assets/29344572/ce8d41f5-b9af-4b68-9b43-8727665cbb24)

Also, this sentence is incorrect:
"The above command will create an file with the name “output.php.gif” which simply need to be upload durning the check..."

Should be: 
"The above command will create a file with the name “output.php.gif” which simply needs to be uploaded during the check..."

**Comment by Prakhar-Shankar** [comment]
Is this issue still open?

**Comment by 5t00g1t** [comment]
Best to look for those mistakes in the page to see if they are still there?

**Comment by Prakhar-Shankar** [comment]
/ assign

**Comment by manthan-sharma-23** [comment]
> Hi there, apologies if I am not following the correct procedure but wanted to let you know about a few grammar mistakes on this page: https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload
> 
> Should be ‘needs’ ![image](https://user-images.githubusercontent.com/29344572/244756334-38081579-5de4-44fb-9b71-ed6a73835a22.png)
> 
> Should be ’in 'a' gif file ![image](https://user-images.githubusercontent.com/29344572/244756400-ce8d41f5-b9af-4b68-9b43-8727665cbb24.png)
> 
> Also, this sentence is incorrect: "The above command will create an file with the name “output.php.gif” which simply need to be upload durning the check..."
> 
> Should be: "The above command will create a file with the name “output.php.gif” which simply needs to be uploaded during the check..."

Please close this issue as it has been resolved.

**Comment by manthan-sharma-23** [comment]
Please close this issue as it has been resolved already . Thank you.
