### ISSUE TITLE
Sponsors / Supporters should be in order of support not alphabetic order

### ISSUE THREAD

**Issue by anantshri** [OWASP/owasp.github.io#25]
Currently the supporters are in alphabetic order but there are tags like member, gold / silver sponsor. a gold sponsor is far more valuable than a normal member or inverse right now that is not clear.

either we keep sections and members inside those sections or we simply arrange then by membership levels. Also this page should point to details of membership levels and how sponsors / supporters can become supporters

**Comment by ebragger** [comment]
@hblankenship 
I'm also in favor of organizing the [Sponsor listing](https://owasp.org/supporters/) according to Gold / Silver / Member sections. This will show due respect to the higher contributing sponsors while also encouraging increased levels. For example, a Member may be influenced to increase their level if they saw a competitor rose to the Silver, Gold, or even Platinum section. Until there are Platinum members, that section should not exist.

**Comment by Pranav2612000** [comment]
I'll like to work on this issue. Seems a simple issue which will also help me in knowing the source code.

**Comment by amruta-kashikar** [comment]
Is this issue still open? I am new to open source and it appears to be a good issue for starting contribution.

**Comment by hblankenship** [comment]
Staff director of sponsorships indicated that the preference here was alphabetical at this time.
