### ISSUE TITLE
Site is unusable with JavaScript disabled

### ISSUE THREAD

**Issue by rbsec** [OWASP/owasp.github.io#27]
The new site design has an empty div that covers the entire page called "blocker" which means that you can't interact with any of the elements in the page (links, forms, etc) without having to enable JavaScript:

```html
    <div id="blocker"></div>
```

This includes the `<noscript>` tag shown at the bottom of the page, which has an unusable link.

Forcing users to enable JavaScript when there's isn't key functionality that requires it is very hostile design, and isn't something that we should be encouraging, especially given that our audience is more security conscious than most people, and will have a higher number of people who block JS for security.

**Comment by securestep9** [comment]
ability to use the site with JavaScript disabled is also  important for accessibility reasons

**Comment by oxdef** [comment]
It will be great if to user is not required to use JavaScript to navigate to owasp site.
