### ISSUE TITLE
Refactor Blog Excerpts

### ISSUE THREAD

**Issue by mikemccamon** [OWASP/owasp.github.io#28]
Some blog/news posts may have introductory content that isn't technically excerpt material. For instance, press releases have a lot of "Front content" that shouldn't be in an excerpt. So at some point we should allow for front matter explicit excerpt and if not there, take post down to excerpt delimiter. Technically we could also just truncate at first char(13) for default excerpt unless there's an explicit one.

**Comment by hblankenship** [comment]
No longer sure what this means; the blog posts have an excerpt functionality already.
