### ISSUE TITLE
Search results on owasp.org have absolute links to www2.owasp.org

### ISSUE THREAD

**Issue by securestep9** [OWASP/owasp.github.io#36]
Looks like the search results on www.owasp.org have www2.owas.org hardcoded in them:

![Screen Shot 2020-01-17 at 15 11 37](https://user-images.githubusercontent.com/20112179/72623639-6f38c080-393d-11ea-9776-562f4660dc2e.png)

**Comment by hblankenship** [comment]
It isn't hard-coded and requires Google to catch up.  This probably won't change for us for a little while.  :/

**Comment by securestep9** [comment]
I this this is because www  dropped from www.owasp.org 
If you search Google for "site: www.owasp.org London" only the www links are returned, but if you search site:owasp.org London both www2 and www links are returned because owasp.org  is a subdomain , so if I search for London I even get results from lists.owasp.org 

Perhaps a solution is to disallow Search Engines from www2? some sort of a dynamic robots.txt - if URL requested starts from  www.owasp.org or owasp.org -> allow search engines, if www2 -> disallow search engines?
