### ISSUE TITLE
Links to www2.owasp.org chapter pages on https://owasp.org/chapters/

### ISSUE THREAD

**Issue by oxdef** [OWASP/owasp.github.io#37]
Steps to reproduce:
1. Navigate to https://owasp.org/chapters/

Actual result:
See links to www2.owasp.org pages, e.g. https://www2.owasp.org/www-chapter-moscow/

Expected result:
https://owasp.org/www-chapter-moscow/

**Comment by hblankenship** [comment]
Thanks. This should be resolved after tonights rebuild of the site json files.

**Comment by cw-owasp** [comment]
Internal owasp.org search results still link to the www2 site:

e.g. https://owasp.org/search/?searchString=moscow
e.g. https://owasp.org/search/?searchString=automated

**Comment by hblankenship** [comment]
This is due, we believe, to a latency in google search updates and should
be resolved over time.


Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

**Comment by oxdef** [comment]
Fixed, thanks!
