### ISSUE TITLE
Membership signup fails - Australia

### ISSUE THREAD

**Issue by digitalstreets** [OWASP/owasp.github.io#46]
When trying to signup using country option "Australia" the membership application fails silently.

Error behind the scenes is as follows:

HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR)POST - https://owaspadmin.azurewebsites.net/api/CreateCheckoutSession?code=ulMNYVfgzBytI1adat1lS6MQ3NabtwKE4IgCJ8yKuhvbFoQh6nOYaw==

**Comment by hblankenship** [comment]
OBE and no longer happens. We have Australian members post this issue.
