### ISSUE TITLE
Membership renewal submit is blocked by CORS policy

### ISSUE THREAD

**Issue by pmvanvliet** [OWASP/owasp.github.io#47]
At https://owasp.org/manage-membership/ the submit button is blocked. See logfile.

[owasp.org-1579612446623.log](https://github.com/OWASP/owasp.github.io/files/4091209/owasp.org-1579612446623.log)

**Comment by hblankenship** [comment]
OBE. This looks to have been resolved. Secondary issue of 'Renew' is that membership renewal is the same as Join
