### ISSUE TITLE
Disclaimer at the bottom of the site has redundancy.

### ISSUE THREAD

**Issue by imthenachoman** [OWASP/owasp.github.io#52]
This is what I see at the bottom of the site.

> Open Web Application Security Project, OWASP, Global AppSec, AppSec Days, AppSec California, SnowFROC, LASCON, and the OWASP logo are trademarks of the OWASP Foundation. **Unless otherwise specified**, all content on the site is Creative Commons Attribution-ShareAlike v4.0 **unless otherwise noted** and provided without warranty of service or accuracy. For more information, please refer to our General Disclaimer. Copyright 2020, OWASP Foundation, Inc.

I've bolded the redundant parts.

**Comment by hackmajor** [comment]
This would definitely be something that legal should review.

**Comment by imthenachoman** [comment]
Agreed. The banner on the top said to post here so I did. But it looks like its been fixed now. :)
