### ISSUE TITLE
Membership renewal doesn't have option to edit or renew

### ISSUE THREAD

**Issue by SoBart-ISO** [OWASP/owasp.github.io#56]
(Perhaps the same as #47)
I want to renew my membership, log in and get the billing/membership overview on page https://owasp.org/manage-membership. I cannot find anywhere a button or myspace, to start the process of adjusting the information or renew my membership.
Using Windows10/Chrome.

**Comment by SoBart-ISO** [comment]
This is all I get...
![image](https://user-images.githubusercontent.com/56998892/73075746-e251b200-3ebc-11ea-968a-e18f5c96244a.png)

**Comment by mikemccamon** [comment]
Correct. The new workflow is you simply buy another membership (whichever team you’d like) and the system will append that term to your record. Email address is the primary key. There is no longer a portal to log into to for membership. 

Seems like we need to add this detail to the emails and manage-membership result page. 

====================
Mike McCamon
Executive Director, OWASP
913.940.2737
Sent while mobile so please excuse typos

**Comment by SoBart-ISO** [comment]
Thank you for the very quick answer. I’ll be happy to pay for another year 😊

Regards/Groet, Bart

**Comment by SoBart-ISO** [comment]
Hi,

I think the new flow is not working as expected. 
On 18-Jan  I received the notification that my membership needs renewal per 18-Mar. In my attempt to renew I got stuck on the new website and created this ticket.
Mike McCamon told me that I had to create a new membership, which automatically would be appended to the existing one. And now a new membership is started. Please reset and append to the existing one.
Message with rest of info sent to info@owasp.org.

Regards, Bart

**Comment by hblankenship** [comment]
Hello, Bart, your data looks correct (see below):
membership start date: 03/19/2019
membership end date: 03/18/2021

**Comment by SoBart-ISO** [comment]
Thank you again for the quick responds!
Then it looks only a mail issue. I received a ‘Thank you for joining OWASP--Welcome!’ mail with the following line: As a reminder, your membership term is 01/27/2020 until 03/18/2021.
The issue is finished for me, but perhaps for you an update on this part of the process.
(BTW. A very nice job on the full redesign of the COMPLETE area ;-)

Regards/Groet, Bart

**Comment by KenProle** [comment]
I experienced the same issue. I received an e-mail from OWASP asking me to renew, taking me to https://owasp.org/membership/. And there it says "You can Manage your Membership to renew an existing plan or modify billing details." I clicked that which takes me to https://owasp.org/manage-membership/, so I entered my e-mail address there to gain access to "manage your information", but i never received an e-mail response (I checked spam). Based on this thread, it sounds like everyone needs to just sign-up again. If so we should change the messaging here - https://owasp.org/membership/. We want to get this right so we don't lose people trying to renew and getting confused.

**Comment by SoBart-ISO** [comment]
I keep receiving renewal requirement notifications. Now I've got 15 days left till end of membership...
When checking the registration, it's OK till Next year.
I think there are still processes active that do not identify me as a renewal. And I think, all other renewals with me.

**Comment by anantshri** [comment]
So many months since this issue is raised and still action is not taken to correct the wordings on the website. Here is my relevant discussion on global board mailing list. https://groups.google.com/a/owasp.org/forum/#!topic/global-board/1fAq2c9BjqA

also refer https://github.com/OWASP/owasp.github.io/issues/47 as another think to look at.

refer: https://groups.google.com/a/owasp.org/d/msg/global-board/1fAq2c9BjqA/5rJ8pUBOAwAJ It seems no test environment is in place and prod is acting like a test environment.


I have create a pull request to this regard : https://github.com/OWASP/owasp.github.io/pull/90

**Comment by hblankenship** [comment]
Per the PR, this was resolved to reflect what manage membership is for and there is now a membership portal for other items
