### ISSUE TITLE
Multiple year membership process is broken

### ISSUE THREAD

**Issue by roberto-at-acrosec** [OWASP/owasp.github.io#59]
Hi, I got an email to renew my membership some days ago (Jan. 25th) stating that it will end. "We have good news and bad news. The bad? Your OWASP membership expires today. " 

However, I am having a multi year membership which ends next year. I checked then (Jan. 25th) the available membership information which correctly stated: 

Manage Your Information
Membership Type: Two Year Membership
Membership Ends On: 1/24/2021

Yesterday (Feb. 2nd) I got another email saying "We are sorry that you decided not to renew your OWASP Foundation Membership."

Seems something is broken on your side. Or maybe this was a phishing attempt as it proposes to see the mail in a browser? I would rather not try a fishy link as us17.campaign-archive.com with cryptic payload. Anyway, please have a look at the membership process as I think these emails might really be from OWASP...

Below the latest screenshot from today which still correctly states that I am a member.
![OWASP membership issue Screenshot from 2020-02-03 11:11:56](https://user-images.githubusercontent.com/60588990/73620570-f001f700-4675-11ea-8aef-64fcda6e4a47.png)

Kind regards,
Roberto

**Comment by mikemccamon** [comment]
Contact me directly at mike@owasp.com with your email address so I can do some more research. We seem to have a small intermittent bug where renewed members still receive the 7-day expired reminder.

**Comment by roberto-at-acrosec** [comment]
You got a pm. 
Btw. I live in Japan. The date will be off by one day in case you want to verify the logs.

**Comment by mikemccamon** [comment]
After going back and forth with Mailchimp (the service provider) we discovered a mis-configured email date which was causing you to erroneously get the "sorry you've expired" message. This is getting corrected. Sorry for the confusion - and THANKS for sending it to us.
