### ISSUE TITLE
Links in automated emails contradict best security practice

### ISSUE THREAD

**Issue by roberto-at-acrosec** [OWASP/owasp.github.io#65]
Hi, when I receive automatically generated emails from OWASP they contain links which go against what OWASP stands for. Below 4 email examples coming from @owasp.org. 

The manage your account example is legit because it comes a few seconds after you click on the manage your account button on the web site. Still leaves a bad taste afterwards. The other ones also seem to be related with OWASP but who in our community would click on them? 

Should be corrected imho because it goes against best practice. 
In a real phishing case, everyone would rightfully blame the user having clicked such fishy links.  

Kind regards, Roberto 

-----------------------------
In the notification mail that the membership expires today:
View this email in your browser (https://us17.campaign-archive.com/?u=a...

Notification mail you receive when you click on the manage your account button on the website: 
Manage your Account <https://u13...76.ct.sendgrid.net/ls/click?upn=...

Info mail regarding a project summit:
View this email in your browser (https://mailchi.mp/owasp/project-summit-winter-2020-selections?e=d...

Info mail regarding 11 Days till AppSec USA 2018, San Jose, CA:
Have you registered? View this email in your browser (https://mailchi.mp/a8dee6cf9...

**Comment by mikemccamon** [comment]
Yes each of these examples uses a third party service to direct users to the proper place on our site. Regrettably unless OWASP stands up their own email tool, we will have to live with this unfortunate setup.  That said, we have tried to use VERY reputable partners to deliver services to members at the most affordable cost - SendGrid, Stripe, Github, and Mailchimp.
