### ISSUE TITLE
gmail fails to deliever to membership@owasp.org email address 

### ISSUE THREAD

**Issue by jz-ang** [OWASP/owasp.github.io#66]
I had a question regarding the status of my membership and sent an email to membership@owasp.org, which is listed as the email address if one has questions regarding membership.

Gmail informs that email delivery to membership@owasp.org failed.

**Comment by mikemccamon** [comment]
Good catch. We will need to fix this.

**Comment by latf6711** [comment]
This was fixed on March 13, 2020

**Comment by mllanes** [comment]
Hi all,
This appears to be an ongoing issue still:

```
** Delivery incomplete **

There was a temporary problem delivering your message to membership@owasp.org. Gmail will retry for 142 more hours. You'll be notified if the delivery fails permanently.

The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720
[mail.owasp.org 2606:4700:10::ac43:a27: timed out]
[mail.owasp.org 2606:4700:10::6816:1a4d: timed out]
[mail.owasp.org 2606:4700:10::6816:1b4d: timed out]
[mail.owasp.org 172.67.10.39: timed out]
[mail.owasp.org 104.22.27.77: timed out]
[mail.owasp.org 104.22.26.77: timed out]
```

**Comment by hblankenship** [comment]
If you are sending email to membership@owasp.org, then that is the problem.  The link for the membership email was updated, I believe, to membership@owasp.com.
