### ISSUE TITLE
owasp.org search result ordering

### ISSUE THREAD

**Issue by kingthorin** [OWASP/owasp.github.io#67]
Is `www-pdf-archive` not indexed?

When you search for say "periodic table" (looking for our periodic table of vulnerabilities), results like: https://www.owasp.org/images/archive/3/38/20130722214916%21OWASP_Periodic_Table_-_Letter_Size.pdf come up before https://owasp.org/www-pdf-archive/OWASP_Periodic_Table_-_Letter_Size.pdf

**Comment by martinmarsicano** [comment]
I think this is ok now, isn't?

**Comment by kingthorin** [comment]
Seems to be. Thanks!
