### ISSUE TITLE
Hide sponsorship banners on specific pages

### ISSUE THREAD

**Issue by rbsec** [OWASP/owasp.github.io#69]
Is there a way to hide/remove the large vendor sponsors banners at the bottom of the page for specific content? While I appreciate that this sponsorship is important (and should be displayed on the main pages of the site), where isn't included with technical content it destroys any appearance of independence and vendor neutrality.

For example, on the cheat sheets project I'm quite happy for a random sponsor logo in the footer of the home page, but if you're viewing a specific cheat sheet (for example, the vulnerable dependency management CS), and at the bottom of the page there's a large vendor logo for a commercial product such as WhiteSource (software to identify vulnerable dependencies) with a paragraph of text about how amazing WhiteSource is, then any attempt at vendor neutrality is complete gone, and the whole CS (which talks about how important vulnerability management in dependencies is) basically just becomes an advert for that company.

The cheat sheets (and many other OWASP projects) should be held up as a gold standard for vendor-neutral advice and guidance, and including what are effectively adverts from the sponsors **alongside the technical content** completely undermines that.

Is there any way that we can host content like the cheat sheets on the new site without having these banners in the page, or any other suggestions about how we can overcome this?

**Comment by mikemccamon** [comment]
No, we don't plan to have a way for projects/chapters to hide OWASP Foundation corporate members from any page on the website. The placement/rotation of logos is entirely random and is a way to recognize organizations that support the Foundation. I also believe it is done in a tasteful way that is not confusing to visitors as if their place is an endorsement.

How could we change the presentation to address these issues in a better way?

**Comment by ThunderSon** [comment]
Mike please re-open this so that we can have a public discussion about this and let other people chime in. I will be adding my opinion and what could be done next week 😄
