### ISSUE TITLE
All TLS links are broken (error 404)

### ISSUE THREAD

**Issue by AWSjourney** [OWASP/owasp.github.io#70]
From google.com I typed "OWASP TLS best practices." Google returned https://owasp.org/www-project-cheat-sheets/cheatsheets/Transport_Layer_Protection_Cheat_Sheet

The resulting link provides Error 404 Not Found. I next went to owasp.org home page and chose Search. I typed TLS Cheat Sheets. Every URL returns with Error 404.

The only way to find OWASP Cheat Sheets is to use a cached version of the Google result. With OWASP search there is no working alternative way to get to a cheat sheet.

**Comment by JokerQyou** [comment]
Basically all cheat sheet URLs and some www-community URLs are broken. For example these two:

- https://owasp.org/www-community/attacks/:Category:OWASP_CSRFGuard_Project
- https://owasp.org/www-project-cheat-sheets/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet

I was reading this page https://owasp.org/www-community/attacks/csrf and found many broken links there.

**Comment by rbsec** [comment]
@AWSjourney the cheat sheets are hosted on https://cheatsheetseries.owasp.org - there were some broken links on Google (such as the one in your post), but they should have cleared out by now.

**Comment by johnthepepper** [comment]
@rbsec Is OWASP's server down? Because I can't access the site

**Comment by rbsec** [comment]
@johnthepepper the site is hosted on GitHub pages, and I'm not aware that they have any issues.

**Comment by hblankenship** [comment]
All broken links in www-community should be submitted on the www-community repository. That particular search did not produce any 404 errors in the current iteration.
