### ISSUE TITLE
Broke link from search result 

### ISSUE THREAD

**Issue by BruceGitHub** [OWASP/owasp.github.io#78]
this link extracted from search result is broke 

https://owasp.org/images/4/4e/OWASP-Ionut-Popescu-Less-Known-Web-Application-Vulnerabilities-Stripped.pdf

**Comment by nhajiyani** [comment]
ping @hblankenship

**Comment by hblankenship** [comment]
Please use the PDF-Archive version of the file at https://owasp.org/www-pdf-archive//OWASP-Ionut-Popescu-Less-Known-Web-Application-Vulnerabilities-Stripped.pdf

**Comment by BruceGitHub** [comment]
> Please use the PDF-Archive version of the file at https://owasp.org/www-pdf-archive//OWASP-Ionut-Popescu-Less-Known-Web-Application-Vulnerabilities-Stripped.pdf

Right but the links need to fix or not ?

**Comment by mshalmanov** [comment]
Hello. I check this link and link https://owasp.org/images/4/4e/OWASP-Ionut-Popescu-Less-Known-Web-Application-Vulnerabilities-Stripped.pdf is correct opened.

**Comment by BruceGitHub** [comment]
Thanks for the answer, in effects now it works.
Was fixed maybe...
