### ISSUE TITLE
Donate Form: No way to indicate Project

### ISSUE THREAD

**Issue by ebragger** [OWASP/owasp.github.io#89]
The [Donate form](https://owasp.org/donate/) does not provide any place to indicate a specific project. That would seem to conflict with messaging all over OWASP that donations to specific projects can be made. Would be nice to have a checkbox called "Donate to a Specific Project" that spawns a drop-down of alphabetized Incubator, Lab, and Flagship projects. (Assumption being we don't want specific donations to inactive projects.)

On a side note, adding a "Comments" textbox would allow us to collect potentially valuable feedback from people donating, such as why and how to improve.

Furthermore, it would be a great feature if the project leaders were automatically notified of the contributor's name, donation amount (incl. one-time or recurring), and comments. This would also necessitate a checkbox for "Share my name, contribution amount, and comments with Project Leaders". (With the disclaimer underneath: "Listing as a Project Contributor is at the discretion of OWASP and Project Leaders.")

@hblankenship @mikemccamon @ninjasimon

**Comment by fredfalcon** [comment]
Learned today that you can change the project name from this link - https://owasp.org/donate/?reponame=www-project-bug-logging-tool&title=OWASP+Bug+logging+tool

Useful for individual projects - however the main site can still have a way to select

**Comment by kingthorin** [comment]
@ebragger if you select the donate button in the project’s page it’ll be attributed to the correct project (or chapter).

**Comment by kingthorin** [comment]
@ebragger can this be closed?

**Comment by kingthorin** [comment]
@ebragger can this be closed?

**Comment by BarberCue** [comment]
Can this be closed?

**Comment by hblankenship** [comment]
Closing issue as answered.
