### ISSUE TITLE
Chapter not listed

### ISSUE THREAD

**Issue by eschultze** [OWASP/owasp.github.io#92]
Hello!

I just noticed that our chapter (https://owasp.org/www-chapter-porto-alegre/) is not listed here https://owasp.org/chapters/#SouthAmerica.

Is there anything I need to do in order to update this list? I was about to submit a pull request by changing these 3 files: `_data/chapters.json`, `_data/leaders.json`, and `sitemap.xml`, but I noticed that `_data/chapters.json` is a huge JSON with over 3k lines and it looks like it's generated by a script.

That's the main reason why I'm asking here. Is there another way of updating https://owasp.org/chapters/#SouthAmerica? If so, what are the next steps I should take?

Edit: our chapter was inactive for the past years and is listed as level -1 at `_data/chapters.json`

**Comment by hblankenship** [comment]
This is resolved.  You must remove the default text between  when you update the index.md file.  After 24 hours your chapter should appear on the chapters page.
